version: '3.8'

services:
  react-app:
    build:
      context: ./apartment-frontend/apartment-listing-react
      dockerfile: Dockerfile
    environment:
     - NEXT_PUBLIC_API_URL=http://backend:5001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  react-native-app:
    build:
      context: ./apartment-frontend/apartment-listing-react-native
      dockerfile: Dockerfile
    environment:
     - REACT_APP_API_URL=http://backend:5001/api
    ports:
      - "19006:19006"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: backend
    container_name: backend
    build:
      context: ./apartment-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
